/**
 * lugaresBH.js
 * -----------------------------------------------------------------------------
 * Base de dados curada de lugares para sair em Belo Horizonte e regiao.
 * Tudo estatico (sem backend) seguindo o padrao de "dataset em classe" do
 * DevProfile. O recomendador (recomendar.js) consome essa lista e o bancoGet.js
 * expoe os getters.
 *
 * SCHEMA de cada lugar:
 * @typedef {Object} Lugar
 * @property {number}  id            Identificador unico
 * @property {string|null} foto      URL de foto real (Wikimedia Commons) ou null -> card usa o gradiente da categoria
 * @property {string}  nome          Nome do lugar
 * @property {string}  categoria     'parque'|'praca'|'mirante'|'cultura'|'cafe'|
 *                                    'restaurante'|'bar'|'feira'|'mercado'|
 *                                    'familia'|'shopping'|'regiao'
 * @property {string}  regiao        Regiao de BH ou cidade da RMBH
 * @property {string}  endereco      Endereco / referencia
 * @property {string}  descricao     Resumo curto
 * @property {string}  custo         'gratis'|'barato'|'medio'|'caro'
 * @property {number}  precoMedio    Gasto medio por pessoa em R$ (0 = gratis)
 * @property {string}  faixaPreco    Texto amigavel ("R$ 0", "R$ 25-50")
 * @property {boolean} temComida     Tem comida no local ou colada nele
 * @property {string}  ambiente      'aberto'|'fechado'|'misto'
 * @property {boolean} bebe          Recomendado para ir com bebe
 * @property {string}  bebeObs       Observacao sobre estrutura p/ bebe
 * @property {string[]}periodos      Periodos bons: 'manha'|'tarde'|'noite'
 * @property {Object}  horarios      { 0..6: {abre:'HH:MM', fecha:'HH:MM'} | null }
 *                                    indice 0=Dom ... 6=Sab. null = fechado no dia.
 * @property {number}  nota          Nota media 0-5
 * @property {number}  avaliacoes    Qtde de avaliacoes (estimativa)
 * @property {Object}  idealPessoas  { min, max } - tamanho de grupo ideal
 * @property {string[]}tags          Palavras-chave p/ exibir e filtrar
 * @property {string}  motivo        Por que vale a pena
 * @property {boolean} destaqueHoje  Aparece na vitrine "Hoje para voce"
 */

// ---- helpers de horario (evitam repetir 7 chaves a cada lugar) ----
const FECHADO = null
const dia = (abre, fecha) => ({ abre, fecha })

/** Mesmo horario em todos os dias da semana. */
function todaSemana(abre, fecha) {
    const o = {}
    for (let i = 0; i < 7; i++) o[i] = dia(abre, fecha)
    return o
}

/** 24 horas / acesso livre (praças e orlas publicas). */
function vinte4h() { return todaSemana('00:00', '23:59') }

/**
 * Monta semana customizada. Passe um objeto com chaves seg,ter,qua,qui,sex,sab,dom
 * cada uma como [abre, fecha] ou null. O que faltar fica FECHADO.
 */
function semana({ dom = null, seg = null, ter = null, qua = null, qui = null, sex = null, sab = null }) {
    const m = [dom, seg, ter, qua, qui, sex, sab]
    const o = {}
    m.forEach((v, i) => { o[i] = v ? dia(v[0], v[1]) : FECHADO })
    return o
}

export default class LugaresBH {

    /** Metadados das categorias (rotulo + emoji) usados nos filtros e cards. */
    static categorias = {
        parque: { label: 'Parques', icone: '🌳' },
        praca: { label: 'Praças', icone: '⛲' },
        mirante: { label: 'Mirantes', icone: '🌄' },
        cultura: { label: 'Cultura e museus', icone: '🏛️' },
        cafe: { label: 'Cafés', icone: '☕' },
        restaurante: { label: 'Restaurantes', icone: '🍽️' },
        bar: { label: 'Bares e boemia', icone: '🍻' },
        feira: { label: 'Feiras', icone: '🛍️' },
        mercado: { label: 'Mercados', icone: '🥬' },
        familia: { label: 'Família e crianças', icone: '🧸' },
        shopping: { label: 'Shoppings', icone: '🛒' },
        regiao: { label: 'Bate-volta na região', icone: '🚗' },
    }

    /** Filtro de comida usado na UI. */
    static comidaOpcoes = {
        tanto: 'Tanto faz',
        com: 'Com comida no local',
        sem: 'Sem precisar comer',
    }

    /** Lista principal de lugares. */
    static lista = [
        // ===================== PRAÇAS / MIRANTES (grátis) =====================
        {
            id: 1,
            foto: 'https://upload.wikimedia.org/wikipedia/commons/e/ef/Praca_do_Papa%2C_Belo_Horizonte_%28cropped%29.jpg',
            galeria: [
              "https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Pra%C3%A7a_do_Papa%2C_Mangabeiras%2C_Belo_Horizonte%2C_fevereiro_de_2023_%283%29.jpg/1280px-Pra%C3%A7a_do_Papa%2C_Mangabeiras%2C_Belo_Horizonte%2C_fevereiro_de_2023_%283%29.jpg",
              "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Pra%C3%A7a_do_Papa%2C_Mangabeiras%2C_Belo_Horizonte%2C_fevereiro_de_2023_%281%29.jpg/1280px-Pra%C3%A7a_do_Papa%2C_Mangabeiras%2C_Belo_Horizonte%2C_fevereiro_de_2023_%281%29.jpg",
              "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Pra%C3%A7a_do_Papa%2C_Mangabeiras%2C_Belo_Horizonte%2C_fevereiro_de_2023_%286%29.jpg/1280px-Pra%C3%A7a_do_Papa%2C_Mangabeiras%2C_Belo_Horizonte%2C_fevereiro_de_2023_%286%29.jpg",
            ],
            nome: 'Praça do Papa (Praça Israel Pinheiro)',
            categoria: 'praca',
            regiao: 'Mangabeiras',
            endereco: 'Praça Israel Pinheiro, Mangabeiras',
            descricao: 'Gramado enorme com a melhor vista panorâmica da cidade. Point de piquenique, pôr do sol e food trucks à noite.',
            custo: 'gratis',
            precoMedio: 0,
            faixaPreco: 'R$ 0 (food trucks à parte)',
            temComida: true,
            ambiente: 'aberto',
            bebe: true,
            bebeObs: 'Gramado plano, espaço de sobra pro carrinho e pra esticar a canga.',
            periodos: ['manha', 'tarde', 'noite'],
            horarios: vinte4h(),
            nota: 4.8,
            avaliacoes: 32100,
            idealPessoas: { min: 1, max: 12 },
            tags: ['vista', 'pôr do sol', 'piquenique', 'food truck', 'pet friendly'],
            motivo: 'Pôr do sol e food trucks num só lugar, de graça e com espaço pro bebê.',
            destaqueHoje: true,
        },
        {
            id: 2,
            foto: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/P%C3%B4r-do-Sol_no_Mirante_do_Mangabeiras_%28Belo_Horizonte-MG%29.JPG/1280px-P%C3%B4r-do-Sol_no_Mirante_do_Mangabeiras_%28Belo_Horizonte-MG%29.JPG',
            galeria: [
              "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Mirantemangabeiras.JPG/1280px-Mirantemangabeiras.JPG",
              "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Chevrolet_hall.JPG/1280px-Chevrolet_hall.JPG",
              "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Bairross%C3%A3opedroesantoant%C3%B4nio.JPG/1280px-Bairross%C3%A3opedroesantoant%C3%B4nio.JPG",
            ],
            nome: 'Mirante das Mangabeiras',
            categoria: 'mirante',
            regiao: 'Mangabeiras',
            endereco: 'Av. José do Patrocínio Pontes, Mangabeiras',
            descricao: 'Mirante clássico de BH, vista de 180° da cidade. Lindo no fim de tarde e à noite com a cidade acesa.',
            custo: 'gratis',
            precoMedio: 0,
            faixaPreco: 'R$ 0',
            temComida: true,
            ambiente: 'aberto',
            bebe: true,
            bebeObs: 'Tem guarda-corpo; segure bem a criança perto da mureta.',
            periodos: ['tarde', 'noite'],
            horarios: todaSemana('06:00', '23:00'),
            nota: 4.7,
            avaliacoes: 18700,
            idealPessoas: { min: 1, max: 8 },
            tags: ['vista', 'pôr do sol', 'romântico', 'noturno'],
            motivo: 'Vista de cartão-postal de graça; perfeito pra casal no fim de tarde.',
            destaqueHoje: true,
        },
        {
            id: 3,
            foto: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Pra%C3%A7a_da_Liberdade_-_Belo_Horizonte.jpg/1280px-Pra%C3%A7a_da_Liberdade_-_Belo_Horizonte.jpg',
            galeria: [
              "https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Pra%C3%A7a_da_Liberdade_-_Belo_Horizonte_-_MG.JPG/1280px-Pra%C3%A7a_da_Liberdade_-_Belo_Horizonte_-_MG.JPG",
              "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Secretaria_da_Via%C3%A7%C3%A3o%2C_Pra%C3%A7a_da_Liberdade_01.jpg/1280px-Secretaria_da_Via%C3%A7%C3%A3o%2C_Pra%C3%A7a_da_Liberdade_01.jpg",
              "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Secretaria_da_Via%C3%A7%C3%A3o%2C_Pra%C3%A7a_da_Liberdade_02.jpg/1280px-Secretaria_da_Via%C3%A7%C3%A3o%2C_Pra%C3%A7a_da_Liberdade_02.jpg",
            ],
            nome: 'Praça da Liberdade',
            categoria: 'praca',
            regiao: 'Funcionários',
            endereco: 'Praça da Liberdade, Funcionários',
            descricao: 'Conjunto histórico com jardins, palmeiras imperiais e o Circuito Cultural ao redor. Ótima pra caminhar e visitar museus.',
            custo: 'gratis',
            precoMedio: 0,
            faixaPreco: 'R$ 0',
            temComida: true,
            ambiente: 'aberto',
            bebe: true,
            bebeObs: 'Calçadas largas e planas, ideal pro carrinho.',
            periodos: ['manha', 'tarde', 'noite'],
            horarios: vinte4h(),
            nota: 4.8,
            avaliacoes: 41000,
            idealPessoas: { min: 1, max: 10 },
            tags: ['histórico', 'jardim', 'museus', 'caminhada', 'foto'],
            motivo: 'Cartão-postal verde com museus grátis colados; bom em qualquer clima ameno.',
            destaqueHoje: true,
        },
        {
            id: 4,
            foto: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Pra%C3%A7a_Carlos_Chagas_-_Belo_Horizonte_-_20250503153052.jpg/1280px-Pra%C3%A7a_Carlos_Chagas_-_Belo_Horizonte_-_20250503153052.jpg',
            galeria: [
              "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Xadrez.JPG/1280px-Xadrez.JPG",
              "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Pra%C3%A7a_Carlos_Chagas_-_Belo_Horizonte_-_20250503160236.jpg/1280px-Pra%C3%A7a_Carlos_Chagas_-_Belo_Horizonte_-_20250503160236.jpg",
              "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Pra%C3%A7a_Carlos_Chagas_-_Belo_Horizonte_-_20250503164114.jpg/1280px-Pra%C3%A7a_Carlos_Chagas_-_Belo_Horizonte_-_20250503164114.jpg",
            ],
            nome: 'Praça da Assembleia',
            categoria: 'praca',
            regiao: 'Funcionários',
            endereco: 'Praça da Assembleia, Funcionários',
            descricao: 'Espelho d’água, gramado e fonte. Point tranquilo de fim de tarde, muito usado por famílias e corredores.',
            custo: 'gratis',
            precoMedio: 0,
            faixaPreco: 'R$ 0',
            temComida: false,
            ambiente: 'aberto',
            bebe: true,
            bebeObs: 'Gramado seguro; fique de olho perto do espelho d’água.',
            periodos: ['manha', 'tarde'],
            horarios: vinte4h(),
            nota: 4.6,
            avaliacoes: 9800,
            idealPessoas: { min: 1, max: 8 },
            tags: ['gramado', 'fonte', 'tranquilo', 'corrida'],
            motivo: 'Sossego no fim de tarde, espaço aberto e zero custo.',
            destaqueHoje: false,
        },
        {
            id: 5,
            foto: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Assembl%C3%A9ia_Legislativa_de_Minas_Gerais_-_panoramio.jpg/1280px-Assembl%C3%A9ia_Legislativa_de_Minas_Gerais_-_panoramio.jpg",
            nome: 'Mirante do Belvedere (Big Boi)',
            categoria: 'mirante',
            regiao: 'Belvedere',
            endereco: 'Rua Professor Estêvão Pinto / Belvedere',
            descricao: 'Vista para a Serra do Curral e a cidade. Famoso pelo nascer e pôr do sol.',
            custo: 'gratis',
            precoMedio: 0,
            faixaPreco: 'R$ 0',
            temComida: false,
            ambiente: 'aberto',
            bebe: true,
            bebeObs: 'Área aberta; bom pra carrinho, mas sem muita sombra.',
            periodos: ['manha', 'tarde'],
            horarios: todaSemana('05:30', '19:00'),
            nota: 4.5,
            avaliacoes: 5600,
            idealPessoas: { min: 1, max: 6 },
            tags: ['vista', 'serra', 'pôr do sol', 'foto'],
            motivo: 'Serra do Curral de cenário; ótimo pra foto e respiro rápido.',
            destaqueHoje: false,
        },

        // ===================== PARQUES (grátis / barato) =====================
        {
            id: 6,
            foto: 'https://upload.wikimedia.org/wikipedia/commons/f/f6/Parque_das_Mangabeiras_-_Belo_Horizonte-MG.jpg',
            galeria: [
              "https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Serra_do_Curral_vista_de_dentro_do_Parque_das_Mangabeiras.jpg/1280px-Serra_do_Curral_vista_de_dentro_do_Parque_das_Mangabeiras.jpg",
              "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Parque_BH_01.jpg/1280px-Parque_BH_01.jpg",
              "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Mata_do_Parque_das_Mangabeiras_-_Belo_Horizonte-MG.JPG/1280px-Mata_do_Parque_das_Mangabeiras_-_Belo_Horizonte-MG.JPG",
            ],
            nome: 'Parque das Mangabeiras',
            categoria: 'parque',
            regiao: 'Mangabeiras',
            endereco: 'Av. José do Patrocínio Pontes, 580 - Mangabeiras',
            descricao: 'Maior parque da cidade, na encosta da Serra do Curral. Trilhas, mirantes, parquinho e muita mata.',
            custo: 'gratis',
            precoMedio: 0,
            faixaPreco: 'R$ 0',
            temComida: true,
            ambiente: 'aberto',
            bebe: true,
            bebeObs: 'Tem parquinho e áreas planas; algumas trilhas são íngremes.',
            periodos: ['manha', 'tarde'],
            horarios: semana({ ter: ['08:00', '18:00'], qua: ['08:00', '18:00'], qui: ['08:00', '18:00'], sex: ['08:00', '18:00'], sab: ['08:00', '18:00'], dom: ['08:00', '18:00'] }),
            nota: 4.7,
            avaliacoes: 22400,
            idealPessoas: { min: 1, max: 12 },
            tags: ['natureza', 'trilha', 'parquinho', 'mirante', 'piquenique'],
            motivo: 'Natureza dentro da cidade, parquinho pro bebê e tudo de graça.',
            destaqueHoje: false,
        },
        {
            id: 7,
            foto: 'https://upload.wikimedia.org/wikipedia/commons/0/00/Parque_Municipal_em_Belo_Horizonte.JPG',
            nome: 'Parque Municipal Américo Renné Giannetti',
            categoria: 'parque',
            regiao: 'Centro',
            endereco: 'Av. Afonso Pena, 1377 - Centro',
            descricao: 'Pulmão verde no coração do Centro: lago com pedalinho, coreto e árvores centenárias.',
            custo: 'barato',
            precoMedio: 10,
            faixaPreco: 'R$ 0 (pedalinho ~R$ 10)',
            temComida: true,
            ambiente: 'aberto',
            bebe: true,
            bebeObs: 'Caminhos planos e sombra; pedalinho é a partir de criança maior.',
            periodos: ['manha', 'tarde'],
            horarios: semana({ ter: ['06:00', '18:00'], qua: ['06:00', '18:00'], qui: ['06:00', '18:00'], sex: ['06:00', '18:00'], sab: ['06:00', '18:00'], dom: ['06:00', '18:00'] }),
            nota: 4.5,
            avaliacoes: 16800,
            idealPessoas: { min: 1, max: 10 },
            tags: ['lago', 'pedalinho', 'sombra', 'centro', 'família'],
            motivo: 'Verde e pedalinho no meio do Centro, custo quase zero.',
            destaqueHoje: false,
        },
        {
            id: 8,
            foto: 'https://upload.wikimedia.org/wikipedia/commons/c/ce/Igrejinha_de_S%C3%A3o_Francisco_de_Assis_6.jpeg',
            galeria: [
              "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Igreja_S%C3%A3o_Francisco_na_Pampulha_06.JPG/1280px-Igreja_S%C3%A3o_Francisco_na_Pampulha_06.JPG",
              "https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Vista_da_Igreja_de_S%C3%A3o_Francisco_de_Assis_com_a_Pampulha_ao_Fundo.jpg/1280px-Vista_da_Igreja_de_S%C3%A3o_Francisco_de_Assis_com_a_Pampulha_ao_Fundo.jpg",
              "https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Igreja_S%C3%A3o_Francisco_de_Assis-_Pampulha-_BH-MG.jpg/1280px-Igreja_S%C3%A3o_Francisco_de_Assis-_Pampulha-_BH-MG.jpg",
            ],
            nome: 'Orla / Parque Ecológico da Pampulha',
            categoria: 'parque',
            regiao: 'Pampulha',
            endereco: 'Av. Otacílio Negrão de Lima - Pampulha',
            descricao: 'Caminho da lagoa cartão-postal: Igreja da Pampulha, ciclovia, gramados e vista pro pôr do sol na água.',
            custo: 'gratis',
            precoMedio: 0,
            faixaPreco: 'R$ 0',
            temComida: true,
            ambiente: 'aberto',
            bebe: true,
            bebeObs: 'Orla plana e larga, dos melhores lugares pra empurrar carrinho.',
            periodos: ['manha', 'tarde', 'noite'],
            horarios: vinte4h(),
            nota: 4.6,
            avaliacoes: 28900,
            idealPessoas: { min: 1, max: 12 },
            tags: ['lagoa', 'ciclovia', 'pôr do sol', 'patrimônio', 'caminhada'],
            motivo: 'Pôr do sol na lagoa, espaço infinito pro bebê e de graça.',
            destaqueHoje: true,
        },
        {
            id: 9,
            foto: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Parque_Municipal_Fazenda_Lagoa_do_Nado.jpg/1280px-Parque_Municipal_Fazenda_Lagoa_do_Nado.jpg',
            galeria: [
              "https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Lagoa_do_Nado.jpg/1280px-Lagoa_do_Nado.jpg",
              "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Lagoadonado.jpg/1280px-Lagoadonado.jpg",
            ],
            nome: 'Parque Lagoa do Nado',
            categoria: 'parque',
            regiao: 'Pampulha (Itapoã)',
            endereco: 'Rua Envira, 100 - Itapoã',
            descricao: 'Parque tranquilo com lagoa, trilhas e centro cultural. Bom pra famílias que querem sossego.',
            custo: 'gratis',
            precoMedio: 0,
            faixaPreco: 'R$ 0',
            temComida: false,
            ambiente: 'aberto',
            bebe: true,
            bebeObs: 'Áreas planas e sombreadas, pouca aglomeração.',
            periodos: ['manha', 'tarde'],
            horarios: semana({ ter: ['06:00', '18:00'], qua: ['06:00', '18:00'], qui: ['06:00', '18:00'], sex: ['06:00', '18:00'], sab: ['06:00', '18:00'], dom: ['06:00', '18:00'] }),
            nota: 4.6,
            avaliacoes: 7300,
            idealPessoas: { min: 1, max: 10 },
            tags: ['lagoa', 'trilha', 'sossego', 'família'],
            motivo: 'Sossego de verdade pra família, sem custo.',
            destaqueHoje: false,
        },
        {
            id: 10,
            foto: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Est%C3%A1dio_Governador_Magalh%C3%A3es_Pinto_-_Belo_Horizonte_-_20250409150611.jpg/1280px-Est%C3%A1dio_Governador_Magalh%C3%A3es_Pinto_-_Belo_Horizonte_-_20250409150611.jpg',
            galeria: [
              "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Mineir%C3%A3o_2014.jpg/1280px-Mineir%C3%A3o_2014.jpg",
              "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Vista_do_Mineirinho_e_do_Mineir%C3%A3o%2C_Belo_Horizonte_MG.JPG/1280px-Vista_do_Mineirinho_e_do_Mineir%C3%A3o%2C_Belo_Horizonte_MG.JPG",
              "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Mineirinho%2C_Lagoa_da_Pampulha_e_Mineir%C3%A3o%2C_Belo_Horizonte_MG.JPG/1280px-Mineirinho%2C_Lagoa_da_Pampulha_e_Mineir%C3%A3o%2C_Belo_Horizonte_MG.JPG",
            ],
            nome: 'Esplanada do Mineirão',
            categoria: 'familia',
            regiao: 'Pampulha',
            endereco: 'Esplanada do Mineirão, Pampulha',
            descricao: 'Explanada do estádio vira point de famílias, skatistas e piquenique nos fins de semana.',
            custo: 'gratis',
            precoMedio: 0,
            faixaPreco: 'R$ 0',
            temComida: true,
            ambiente: 'aberto',
            bebe: true,
            bebeObs: 'Piso liso e amplo, ótimo pra carrinho e primeiros passos.',
            periodos: ['manha', 'tarde'],
            horarios: vinte4h(),
            nota: 4.4,
            avaliacoes: 4100,
            idealPessoas: { min: 2, max: 15 },
            tags: ['família', 'skate', 'piquenique', 'amplo'],
            motivo: 'Espaço gigante e plano pra família, colado na orla da Pampulha.',
            destaqueHoje: false,
        },

        // ===================== CULTURA / MUSEUS (grátis / barato) =====================
        {
            id: 11,
            foto: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Centro_Cultural_Banco_do_Brasil%2C_Belo_Horizonte_-_panoramio.jpg/1280px-Centro_Cultural_Banco_do_Brasil%2C_Belo_Horizonte_-_panoramio.jpg',
            galeria: [
              "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Centro_Cultural_Banco_do_Brasil_-_panoramio_%281%29.jpg/1280px-Centro_Cultural_Banco_do_Brasil_-_panoramio_%281%29.jpg",
              "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Centro_Cultural_do_Banco_do_Brasil_%28CCBB%29.jpg/1280px-Centro_Cultural_do_Banco_do_Brasil_%28CCBB%29.jpg",
            ],
            nome: 'CCBB - Centro Cultural Banco do Brasil',
            categoria: 'cultura',
            regiao: 'Centro',
            endereco: 'Praça da Liberdade, 450 - Funcionários',
            descricao: 'Exposições rotativas de alto nível, café e programação infantil. Quase sempre gratuito.',
            custo: 'gratis',
            precoMedio: 0,
            faixaPreco: 'R$ 0 (algumas exposições pagas)',
            temComida: true,
            ambiente: 'fechado',
            bebe: true,
            bebeObs: 'Ambiente climatizado e acessível; plano perfeito pra dia de chuva.',
            periodos: ['manha', 'tarde', 'noite'],
            horarios: semana({ qua: ['10:00', '22:00'], qui: ['10:00', '22:00'], sex: ['10:00', '22:00'], sab: ['10:00', '22:00'], dom: ['10:00', '22:00'], seg: ['10:00', '22:00'] }),
            nota: 4.7,
            avaliacoes: 19500,
            idealPessoas: { min: 1, max: 8 },
            tags: ['exposição', 'arte', 'climatizado', 'plano chuva', 'gratuito'],
            motivo: 'Cultura de graça e coberta — salva o programa se a chuva chegar.',
            destaqueHoje: false,
        },
        {
            id: 12,
            foto: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Memorial_Minas_Gerais_Vale%2C_Belo_Horizonte%2C_Minas_Gerais_-_IMG20231105202039.jpg/1280px-Memorial_Minas_Gerais_Vale%2C_Belo_Horizonte%2C_Minas_Gerais_-_IMG20231105202039.jpg',
            nome: 'Circuito Praça da Liberdade (museus)',
            categoria: 'cultura',
            regiao: 'Funcionários',
            endereco: 'Praça da Liberdade - Memorial Vale, MM Gerdau, Casa Fiat',
            descricao: 'Vários museus em volta da praça: Memorial Minas Gerais Vale, MM Gerdau (minas e metal) e Casa Fiat de Cultura.',
            custo: 'gratis',
            precoMedio: 0,
            faixaPreco: 'R$ 0 (entrada gratuita na maioria)',
            temComida: true,
            ambiente: 'fechado',
            bebe: true,
            bebeObs: 'Climatizados e com acessibilidade; ótimos pra fugir do calor ou da chuva.',
            periodos: ['manha', 'tarde'],
            horarios: semana({ ter: ['10:00', '17:30'], qua: ['10:00', '17:30'], qui: ['10:00', '17:30'], sex: ['10:00', '17:30'], sab: ['10:00', '17:30'], dom: ['10:00', '17:30'] }),
            nota: 4.7,
            avaliacoes: 23800,
            idealPessoas: { min: 1, max: 8 },
            tags: ['museu', 'arte', 'história', 'gratuito', 'plano chuva'],
            motivo: 'Três museus grátis e cobertos a poucos passos um do outro.',
            destaqueHoje: false,
        },
        {
            id: 13,
            foto: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Museu_de_Artes_e_Of%C3%ADcios_2022.jpg/1280px-Museu_de_Artes_e_Of%C3%ADcios_2022.jpg',
            galeria: [
              "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Museu_de_Artes_e_Of%C3%ADcios%2C_Belo_Horizonte%2C_Brasil.JPG/1280px-Museu_de_Artes_e_Of%C3%ADcios%2C_Belo_Horizonte%2C_Brasil.JPG",
              "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Museu_de_Artes_e_Of%C3%ADcios%2C_Belo_Horizonte%2C_Brasil_0.JPG/1280px-Museu_de_Artes_e_Of%C3%ADcios%2C_Belo_Horizonte%2C_Brasil_0.JPG",
              "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Museu_de_Artes_e_Of%C3%ADcios%2C_Belo_Horizonte%2C_Brasil_1.JPG/1280px-Museu_de_Artes_e_Of%C3%ADcios%2C_Belo_Horizonte%2C_Brasil_1.JPG",
            ],
            nome: 'Museu de Artes e Ofícios',
            categoria: 'cultura',
            regiao: 'Centro (Praça da Estação)',
            endereco: 'Praça Rui Barbosa (Praça da Estação) - Centro',
            descricao: 'Acervo sobre o trabalho e os ofícios brasileiros, dentro da antiga estação ferroviária.',
            custo: 'barato',
            precoMedio: 12,
            faixaPreco: 'R$ 12 (meia/gratuito em dias específicos)',
            temComida: false,
            ambiente: 'fechado',
            bebe: true,
            bebeObs: 'Espaços amplos e cobertos; tranquilo com carrinho.',
            periodos: ['manha', 'tarde'],
            horarios: semana({ qua: ['12:00', '19:00'], qui: ['12:00', '19:00'], sex: ['12:00', '19:00'], sab: ['10:00', '17:00'], dom: ['10:00', '17:00'] }),
            nota: 4.6,
            avaliacoes: 6900,
            idealPessoas: { min: 1, max: 6 },
            tags: ['museu', 'história', 'estação', 'plano chuva'],
            motivo: 'Cultura barata e coberta no coração histórico da cidade.',
            destaqueHoje: false,
        },

        // ===================== CAFÉS =====================
        {
            id: 14,
            foto: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Museu_de_Artes_e_Of%C3%ADcios%2C_Belo_Horizonte%2C_Brasil.JPG/1280px-Museu_de_Artes_e_Of%C3%ADcios%2C_Belo_Horizonte%2C_Brasil.JPG",
            galeria: [
              "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Museu_de_Artes_e_Of%C3%ADcios%2C_Belo_Horizonte%2C_Brasil_0.JPG/1280px-Museu_de_Artes_e_Of%C3%ADcios%2C_Belo_Horizonte%2C_Brasil_0.JPG",
              "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Museu_de_Artes_e_Of%C3%ADcios%2C_Belo_Horizonte%2C_Brasil_1.JPG/1280px-Museu_de_Artes_e_Of%C3%ADcios%2C_Belo_Horizonte%2C_Brasil_1.JPG",
            ],
            nome: 'Café com Letras',
            categoria: 'cafe',
            regiao: 'Savassi',
            endereco: 'Rua Antônio de Albuquerque, 781 - Savassi',
            descricao: 'Café-livraria tradicional da Savassi, ótimo pra brunch, leitura e papo tranquilo.',
            custo: 'medio',
            precoMedio: 45,
            faixaPreco: 'R$ 30-60 por pessoa',
            temComida: true,
            ambiente: 'fechado',
            bebe: true,
            bebeObs: 'Ambiente calmo e climatizado; tem espaço entre mesas.',
            periodos: ['manha', 'tarde', 'noite'],
            horarios: semana({ seg: ['09:00', '22:00'], ter: ['09:00', '22:00'], qua: ['09:00', '22:00'], qui: ['09:00', '23:00'], sex: ['09:00', '23:00'], sab: ['09:00', '23:00'], dom: ['09:00', '18:00'] }),
            nota: 4.6,
            avaliacoes: 8700,
            idealPessoas: { min: 1, max: 6 },
            tags: ['café', 'brunch', 'livraria', 'climatizado'],
            motivo: 'Brunch gostoso e coberto; bom em dia de chuva ou frio.',
            destaqueHoje: false,
        },
        {
            id: 15,
            foto: null,
            nome: 'Cuppa Coffee Roasters',
            categoria: 'cafe',
            regiao: 'Savassi / Lourdes',
            endereco: 'Rua Sergipe, Savassi',
            descricao: 'Café especial torrado na casa, queridinho de quem curte um espresso bem feito.',
            custo: 'barato',
            precoMedio: 25,
            faixaPreco: 'R$ 15-35 por pessoa',
            temComida: true,
            ambiente: 'misto',
            bebe: true,
            bebeObs: 'Tem mesinhas na calçada; ambiente pequeno mas tranquilo.',
            periodos: ['manha', 'tarde'],
            horarios: semana({ seg: ['08:00', '19:00'], ter: ['08:00', '19:00'], qua: ['08:00', '19:00'], qui: ['08:00', '19:00'], sex: ['08:00', '19:00'], sab: ['09:00', '17:00'] }),
            nota: 4.7,
            avaliacoes: 4300,
            idealPessoas: { min: 1, max: 4 },
            tags: ['café especial', 'espresso', 'barato'],
            motivo: 'Café especial sem pesar no bolso; parada rápida e gostosa.',
            destaqueHoje: false,
        },
        {
            id: 16,
            foto: null,
            nome: 'Birosca dos Cafés / cafés do Mercado Novo',
            categoria: 'cafe',
            regiao: 'Centro (Mercado Novo)',
            endereco: 'Av. Olegário Maciel - Mercado Novo, Centro',
            descricao: 'Cafés e torrefações dentro do Mercado Novo, somando café especial com a vibe alternativa do lugar.',
            custo: 'barato',
            precoMedio: 20,
            faixaPreco: 'R$ 12-30 por pessoa',
            temComida: true,
            ambiente: 'misto',
            bebe: false,
            bebeObs: 'Corredores apertados e cheios à noite; melhor de dia com o bebê.',
            periodos: ['manha', 'tarde'],
            horarios: semana({ seg: ['09:00', '18:00'], ter: ['09:00', '18:00'], qua: ['09:00', '18:00'], qui: ['09:00', '22:00'], sex: ['09:00', '23:00'], sab: ['09:00', '20:00'] }),
            nota: 4.5,
            avaliacoes: 5200,
            idealPessoas: { min: 1, max: 6 },
            tags: ['café', 'alternativo', 'barato', 'descolado'],
            motivo: 'Café especial barato no point mais descolado do Centro.',
            destaqueHoje: false,
        },

        // ===================== MERCADOS / FEIRAS =====================
        {
            id: 17,
            foto: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Mercado_Central%2C_Belo_Horizonte%2C_Minas_Gerais_-_2023-11-05_-_DSC01893_%28cropped%29.jpg/1280px-Mercado_Central%2C_Belo_Horizonte%2C_Minas_Gerais_-_2023-11-05_-_DSC01893_%28cropped%29.jpg',
            galeria: [
              "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Entrada_do_Mercado_Central_de_Belo_Horizonte%2C_2022.jpg/1280px-Entrada_do_Mercado_Central_de_Belo_Horizonte%2C_2022.jpg",
              "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Mercado_Central_de_Belo_Horizonte_-_Belo_Horizonte_-_20220213103625.jpg/1280px-Mercado_Central_de_Belo_Horizonte_-_Belo_Horizonte_-_20220213103625.jpg",
              "https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Mercado_Central_de_Belo_Horizonte_-_Belo_Horizonte_-_20220213103759.jpg/1280px-Mercado_Central_de_Belo_Horizonte_-_Belo_Horizonte_-_20220213103759.jpg",
            ],
            nome: 'Mercado Central',
            categoria: 'mercado',
            regiao: 'Centro',
            endereco: 'Av. Augusto de Lima, 744 - Centro',
            descricao: 'Ícone de BH: queijos, cachaças, bares de boteco e o famoso fígado com jiló. Cheio e animado.',
            custo: 'barato',
            precoMedio: 35,
            faixaPreco: 'R$ 20-60 por pessoa',
            temComida: true,
            ambiente: 'fechado',
            bebe: false,
            bebeObs: 'Muito cheio e barulhento; difícil circular com carrinho.',
            periodos: ['manha', 'tarde'],
            horarios: semana({ seg: ['07:00', '18:00'], ter: ['07:00', '18:00'], qua: ['07:00', '18:00'], qui: ['07:00', '18:00'], sex: ['07:00', '18:00'], sab: ['07:00', '18:00'], dom: ['07:00', '13:00'] }),
            nota: 4.7,
            avaliacoes: 88000,
            idealPessoas: { min: 2, max: 8 },
            tags: ['boteco', 'queijo', 'cachaça', 'tradicional', 'coberto'],
            motivo: 'A alma boêmia de BH coberta; ótimo petisco barato (sem o bebê no horário de pico).',
            destaqueHoje: false,
        },
        {
            id: 18,
            foto: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Mercado_Central_de_Belo_Horizonte_-_Belo_Horizonte_-_20220213103625.jpg/1280px-Mercado_Central_de_Belo_Horizonte_-_Belo_Horizonte_-_20220213103625.jpg",
            galeria: [
              "https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Mercado_Central_de_Belo_Horizonte_-_Belo_Horizonte_-_20220213103759.jpg/1280px-Mercado_Central_de_Belo_Horizonte_-_Belo_Horizonte_-_20220213103759.jpg",
              "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Mercado_Central_de_Belo_Horizonte_-_Belo_Horizonte_-_20220213104142.jpg/1280px-Mercado_Central_de_Belo_Horizonte_-_Belo_Horizonte_-_20220213104142.jpg",
            ],
            nome: 'Mercado Novo',
            categoria: 'mercado',
            regiao: 'Centro',
            endereco: 'Av. Olegário Maciel, 333 - Centro',
            descricao: 'Antigo mercado que virou polo de bares, cervejarias e arte. Vibe jovem, principalmente à noite.',
            custo: 'barato',
            precoMedio: 40,
            faixaPreco: 'R$ 25-60 por pessoa',
            temComida: true,
            ambiente: 'fechado',
            bebe: false,
            bebeObs: 'Cheio e barulhento à noite; vá de dia se for com o bebê.',
            periodos: ['tarde', 'noite'],
            horarios: semana({ ter: ['12:00', '22:00'], qua: ['12:00', '23:00'], qui: ['12:00', '00:00'], sex: ['12:00', '00:00'], sab: ['12:00', '00:00'], dom: ['12:00', '18:00'] }),
            nota: 4.6,
            avaliacoes: 21000,
            idealPessoas: { min: 2, max: 10 },
            tags: ['bar', 'cerveja', 'arte', 'jovem', 'noturno'],
            motivo: 'Bares e cervejas artesanais baratas num galpão cheio de arte.',
            destaqueHoje: false,
        },
        {
            id: 19,
            foto: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Mercado_Novo_de_Belo_Horizonte.jpg/1280px-Mercado_Novo_de_Belo_Horizonte.jpg",
            galeria: [
              "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Mercado_Novo_em_BH_01.jpg/1280px-Mercado_Novo_em_BH_01.jpg",
              "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Mercado_Novo_em_BH_02.jpg/1280px-Mercado_Novo_em_BH_02.jpg",
            ],
            nome: 'Feira Hippie (Av. Afonso Pena)',
            categoria: 'feira',
            regiao: 'Centro',
            endereco: 'Av. Afonso Pena - Centro (domingos)',
            descricao: 'Maior feira de artesanato da cidade, só aos domingos de manhã. Comidas típicas, artesanato e tradição.',
            custo: 'barato',
            precoMedio: 25,
            faixaPreco: 'R$ 0 a passear / R$ 10-40 comprando',
            temComida: true,
            ambiente: 'aberto',
            bebe: true,
            bebeObs: 'Bem cheia; ande pelas bordas com o carrinho.',
            periodos: ['manha'],
            horarios: semana({ dom: ['07:00', '14:00'] }),
            nota: 4.5,
            avaliacoes: 30500,
            idealPessoas: { min: 1, max: 8 },
            tags: ['artesanato', 'tradição', 'domingo', 'comida típica'],
            motivo: 'Programa de domingo de manhã clássico de BH, custa o que você quiser.',
            destaqueHoje: false,
        },

        // ===================== BARES / BOEMIA (noite) =====================
        {
            id: 20,
            foto: 'https://upload.wikimedia.org/wikipedia/commons/6/6e/Pra%C3%A7a_Savassi_em_Belo_Horizonte.JPG',
            galeria: [
              "https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Free_Hugs_at_Pra%C3%A7a_da_Savassi%2C_Belo_Horizonte%2C_MG_%2C_Brazil.jpg/1280px-Free_Hugs_at_Pra%C3%A7a_da_Savassi%2C_Belo_Horizonte%2C_MG_%2C_Brazil.jpg",
              "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Pr%C3%A9dios_na_Savassi%2C_Belo_Horizonte_MG.JPG/1280px-Pr%C3%A9dios_na_Savassi%2C_Belo_Horizonte_MG.JPG",
              "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/P%C3%B4r_do_sol_na_Savassi%2C_Belo_Horizonte_MG.JPG/1280px-P%C3%B4r_do_sol_na_Savassi%2C_Belo_Horizonte_MG.JPG",
            ],
            nome: 'Quarteirão da Savassi',
            categoria: 'bar',
            regiao: 'Savassi',
            endereco: 'Cruzamento Rua Tomé de Souza com Pernambuco - Savassi',
            descricao: 'Coração da vida noturna: mesas na rua, bares colados e movimento garantido toda noite.',
            custo: 'medio',
            precoMedio: 60,
            faixaPreco: 'R$ 40-90 por pessoa',
            temComida: true,
            ambiente: 'misto',
            bebe: false,
            bebeObs: 'Lotado e barulhento à noite; não é lugar pra bebê depois do anoitecer.',
            periodos: ['noite'],
            horarios: semana({ ter: ['17:00', '00:00'], qua: ['17:00', '00:00'], qui: ['17:00', '01:00'], sex: ['17:00', '02:00'], sab: ['12:00', '02:00'], dom: ['12:00', '23:00'] }),
            nota: 4.5,
            avaliacoes: 17600,
            idealPessoas: { min: 2, max: 12 },
            tags: ['bar', 'noturno', 'movimentado', 'mesa na rua'],
            motivo: 'A noite da Savassi pra quem quer agito e bar na rua.',
            destaqueHoje: false,
        },
        {
            id: 21,
            foto: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/WPGS_20220728_BeloHorizonte_RuaSapucai_P2051666.jpg/1280px-WPGS_20220728_BeloHorizonte_RuaSapucai_P2051666.jpg',
            galeria: [
              "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Viaduto_Santa_Tereza.jpg/1280px-Viaduto_Santa_Tereza.jpg",
              "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Viaduto_Santa_Tereza_Belo_Horizonte%2C_Brasil.jpg/1280px-Viaduto_Santa_Tereza_Belo_Horizonte%2C_Brasil.jpg",
              "https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Viaduto_Santa_Tereza%2C_Belo_Horizonte%2C_Brasil.JPG/1280px-Viaduto_Santa_Tereza%2C_Belo_Horizonte%2C_Brasil.JPG",
            ],
            nome: 'Viaduto Santa Tereza & Rua Sapucaí',
            categoria: 'bar',
            regiao: 'Santa Tereza / Floresta',
            endereco: 'Viaduto Santa Tereza e Rua Sapucaí',
            descricao: 'Boemia raiz de BH: bares embaixo do viaduto e a vista da Sapucaí, point de samba e cerveja gelada.',
            custo: 'barato',
            precoMedio: 35,
            faixaPreco: 'R$ 20-50 por pessoa',
            temComida: true,
            ambiente: 'aberto',
            bebe: false,
            bebeObs: 'Ambiente de boteco lotado à noite; vá só o casal.',
            periodos: ['tarde', 'noite'],
            horarios: semana({ qui: ['17:00', '00:00'], sex: ['17:00', '02:00'], sab: ['15:00', '02:00'], dom: ['15:00', '23:00'] }),
            nota: 4.6,
            avaliacoes: 14200,
            idealPessoas: { min: 2, max: 12 },
            tags: ['boemia', 'samba', 'cerveja', 'vista', 'barato'],
            motivo: 'Boemia barata e autêntica com vista da Sapucaí; clássico de fim de tarde.',
            destaqueHoje: true,
        },

        // ===================== RESTAURANTES =====================
        {
            id: 22,
            foto: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Viaduto_Santa_Tereza.jpg/1280px-Viaduto_Santa_Tereza.jpg",
            galeria: [
              "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Viaduto_Santa_Tereza_Belo_Horizonte%2C_Brasil.jpg/1280px-Viaduto_Santa_Tereza_Belo_Horizonte%2C_Brasil.jpg",
              "https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Viaduto_Santa_Tereza%2C_Belo_Horizonte%2C_Brasil.JPG/1280px-Viaduto_Santa_Tereza%2C_Belo_Horizonte%2C_Brasil.JPG",
            ],
            nome: 'Xapuri (comida mineira)',
            categoria: 'restaurante',
            regiao: 'Pampulha (Mangabeiras p/ ref.)',
            endereco: 'Rua Mandacaru, 260 - Pampulha',
            descricao: 'Comida mineira de fogão a lenha em ambiente rústico e arborizado. Tradição de família.',
            custo: 'caro',
            precoMedio: 90,
            faixaPreco: 'R$ 70-120 por pessoa',
            temComida: true,
            ambiente: 'misto',
            bebe: true,
            bebeObs: 'Ambiente amplo e arejado, com espaço entre mesas; recebe bem família.',
            periodos: ['tarde'],
            horarios: semana({ qua: ['11:30', '16:00'], qui: ['11:30', '16:00'], sex: ['11:30', '16:00'], sab: ['11:30', '17:00'], dom: ['11:30', '17:00'] }),
            nota: 4.7,
            avaliacoes: 12800,
            idealPessoas: { min: 2, max: 12 },
            tags: ['comida mineira', 'fogão a lenha', 'família', 'almoço'],
            motivo: 'Almoço mineiro de verdade num ambiente que recebe bem o bebê.',
            destaqueHoje: false,
        },
        {
            id: 23,
            foto: null,
            nome: 'Dona Lucinha (buffet mineiro)',
            categoria: 'restaurante',
            regiao: 'Funcionários / Savassi',
            endereco: 'Rua Sergipe, 811 - Savassi',
            descricao: 'Buffet de comida mineira com dezenas de pratos típicos. Referência da culinária do estado.',
            custo: 'medio',
            precoMedio: 75,
            faixaPreco: 'R$ 60-100 por pessoa',
            temComida: true,
            ambiente: 'fechado',
            bebe: true,
            bebeObs: 'Climatizado e tranquilo; cadeirinha disponível.',
            periodos: ['tarde', 'noite'],
            horarios: semana({ seg: ['11:30', '15:00'], ter: ['11:30', '15:00'], qua: ['11:30', '15:00'], qui: ['11:30', '22:00'], sex: ['11:30', '22:00'], sab: ['11:30', '22:00'], dom: ['11:30', '16:00'] }),
            nota: 4.6,
            avaliacoes: 9100,
            idealPessoas: { min: 1, max: 10 },
            tags: ['comida mineira', 'buffet', 'climatizado', 'família'],
            motivo: 'Comida mineira completa, coberta e tranquila pra ir com a família.',
            destaqueHoje: false,
        },
        {
            id: 24,
            foto: null,
            nome: 'Pizzarias e mesas da Praça da Savassi',
            categoria: 'restaurante',
            regiao: 'Savassi',
            endereco: 'Entorno da Praça Diogo de Vasconcelos - Savassi',
            descricao: 'Várias opções de pizza, hambúrguer e massas com mesas ao ar livre na praça.',
            custo: 'medio',
            precoMedio: 50,
            faixaPreco: 'R$ 35-70 por pessoa',
            temComida: true,
            ambiente: 'misto',
            bebe: true,
            bebeObs: 'Mesas ao ar livre, dá pra acomodar carrinho na maioria.',
            periodos: ['tarde', 'noite'],
            horarios: todaSemana('11:00', '00:00'),
            nota: 4.4,
            avaliacoes: 11200,
            idealPessoas: { min: 2, max: 10 },
            tags: ['pizza', 'hambúrguer', 'ar livre', 'jantar'],
            motivo: 'Jantar ao ar livre na Savassi, com opção de levar o bebê.',
            destaqueHoje: false,
        },

        // ===================== FAMÍLIA / CRIANÇAS =====================
        {
            id: 25,
            foto: 'https://upload.wikimedia.org/wikipedia/commons/3/38/Tigre_Zoologico_BH_MG_29.09.2007.JPG',
            galeria: [
              "https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Zool%C3%B3gico_municipal_de_Belo_Horizonte_-_MG.jpg/1280px-Zool%C3%B3gico_municipal_de_Belo_Horizonte_-_MG.jpg",
              "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Zool%C3%B3gico_Municipal_de_Belo_Horizonte_-_MG.jpg/1280px-Zool%C3%B3gico_Municipal_de_Belo_Horizonte_-_MG.jpg",
              "https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Zool%C3%B3gico_municipal_de_Belo_Horizonte_MG.jpg/1280px-Zool%C3%B3gico_municipal_de_Belo_Horizonte_MG.jpg",
            ],
            nome: 'Zoológico de BH (Fundação Zoo-Botânica)',
            categoria: 'familia',
            regiao: 'Pampulha',
            endereco: 'Av. Otacílio Negrão de Lima, 8000 - Pampulha',
            descricao: 'Zoo grande e arborizado na Pampulha, com aquário e jardim botânico no mesmo complexo.',
            custo: 'barato',
            precoMedio: 15,
            faixaPreco: 'R$ 12-20 (entrada)',
            temComida: true,
            ambiente: 'aberto',
            bebe: true,
            bebeObs: 'Caminhos largos e planos; programa pensado pra família.',
            periodos: ['manha', 'tarde'],
            horarios: semana({ ter: ['08:30', '17:00'], qua: ['08:30', '17:00'], qui: ['08:30', '17:00'], sex: ['08:30', '17:00'], sab: ['08:30', '17:00'], dom: ['08:30', '17:00'] }),
            nota: 4.6,
            avaliacoes: 26400,
            idealPessoas: { min: 2, max: 12 },
            tags: ['zoo', 'animais', 'aquário', 'família', 'barato'],
            motivo: 'Passeio em família barato, com aquário e bichos pra criançada.',
            destaqueHoje: false,
        },
        {
            id: 26,
            foto: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Zool%C3%B3gico_municipal_de_Belo_Horizonte_-_MG.jpg/1280px-Zool%C3%B3gico_municipal_de_Belo_Horizonte_-_MG.jpg",
            galeria: [
              "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Tigre_Zoologico_BH_MG_29.09.2007.JPG/1280px-Tigre_Zoologico_BH_MG_29.09.2007.JPG",
              "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Elefante_Zoo_Belo_Horizonte.jpg/1280px-Elefante_Zoo_Belo_Horizonte.jpg",
            ],
            nome: 'Parque Guanabara (diversões)',
            categoria: 'familia',
            regiao: 'Pampulha',
            endereco: 'Av. Otacílio Negrão de Lima - Pampulha',
            descricao: 'Parque de diversões histórico da Pampulha, com brinquedos pra todas as idades.',
            custo: 'medio',
            precoMedio: 50,
            faixaPreco: 'R$ 40-70 (passaporte)',
            temComida: true,
            ambiente: 'aberto',
            bebe: true,
            bebeObs: 'Tem área baby; brinquedos infantis pra bebê maior.',
            periodos: ['tarde', 'noite'],
            horarios: semana({ sex: ['16:00', '22:00'], sab: ['14:00', '22:00'], dom: ['14:00', '21:00'] }),
            nota: 4.4,
            avaliacoes: 13900,
            idealPessoas: { min: 2, max: 12 },
            tags: ['diversões', 'brinquedos', 'família', 'noturno'],
            motivo: 'Diversão garantida em família; abre até a noite no fim de semana.',
            destaqueHoje: false,
        },

        // ===================== SHOPPINGS (plano chuva / noite) =====================
        {
            id: 27,
            foto: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Parque_Guanabara_-_Belo_Horizonte.jpg/1280px-Parque_Guanabara_-_Belo_Horizonte.jpg",
            galeria: [
              "https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/MIRAGE_PARQUE_GUANABARA.jpg/1280px-MIRAGE_PARQUE_GUANABARA.jpg",
            ],
            nome: 'Pátio Savassi',
            categoria: 'shopping',
            regiao: 'Savassi',
            endereco: 'Av. do Contorno, 6061 - Savassi',
            descricao: 'Shopping a céu aberto na Savassi, com praça de alimentação, cinema e lojas.',
            custo: 'barato',
            precoMedio: 30,
            faixaPreco: 'R$ 0 a passear / R$ 25-60 comendo',
            temComida: true,
            ambiente: 'fechado',
            bebe: true,
            bebeObs: 'Fraldário, climatizado e fácil com carrinho — plano de chuva certeiro.',
            periodos: ['tarde', 'noite'],
            horarios: semana({ seg: ['10:00', '22:00'], ter: ['10:00', '22:00'], qua: ['10:00', '22:00'], qui: ['10:00', '22:00'], sex: ['10:00', '22:00'], sab: ['10:00', '22:00'], dom: ['13:00', '21:00'] }),
            nota: 4.5,
            avaliacoes: 30200,
            idealPessoas: { min: 1, max: 10 },
            tags: ['shopping', 'cinema', 'climatizado', 'plano chuva', 'fraldário'],
            motivo: 'Salva o dia de chuva: coberto, com fraldário e aberto até a noite.',
            destaqueHoje: false,
        },
        {
            id: 28,
            foto: 'https://upload.wikimedia.org/wikipedia/commons/e/e3/Bhshopping.JPG',
            galeria: [
              "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Estacionamentobhshopping.JPG/1280px-Estacionamentobhshopping.JPG",
              "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Senhora_do_carmo.JPG/1280px-Senhora_do_carmo.JPG",
              "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Bhshoppingestacionamento.JPG/1280px-Bhshoppingestacionamento.JPG",
            ],
            nome: 'BH Shopping',
            categoria: 'shopping',
            regiao: 'Belvedere',
            endereco: 'Rod. BR-356, 3049 - Belvedere',
            descricao: 'Um dos maiores shoppings da cidade, com cinema, parque infantil e ampla praça de alimentação.',
            custo: 'barato',
            precoMedio: 35,
            faixaPreco: 'R$ 0 a passear / R$ 25-70 comendo',
            temComida: true,
            ambiente: 'fechado',
            bebe: true,
            bebeObs: 'Estrutura completa pra bebê: fraldário, espaço kids e climatização.',
            periodos: ['tarde', 'noite'],
            horarios: semana({ seg: ['10:00', '22:00'], ter: ['10:00', '22:00'], qua: ['10:00', '22:00'], qui: ['10:00', '22:00'], sex: ['10:00', '22:00'], sab: ['10:00', '22:00'], dom: ['13:00', '21:00'] }),
            nota: 4.6,
            avaliacoes: 41800,
            idealPessoas: { min: 1, max: 10 },
            tags: ['shopping', 'cinema', 'espaço kids', 'plano chuva', 'fraldário'],
            motivo: 'Plano de chuva com tudo pro bebê e diversão pra todos.',
            destaqueHoje: false,
        },

        // ===================== BATE-VOLTA NA REGIÃO =====================
        {
            id: 29,
            foto: 'https://upload.wikimedia.org/wikipedia/commons/a/a3/Inhotim_-_panoramio_%28cropped%29.jpg',
            galeria: [
              "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Ahearn_Torres_Inhotim_Brumadinho_01.jpg/1280px-Ahearn_Torres_Inhotim_Brumadinho_01.jpg",
              "https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Ahearn_Torres_Inhotim_Brumadinho_02.jpg/1280px-Ahearn_Torres_Inhotim_Brumadinho_02.jpg",
              "https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Ahearn_Torres_Inhotim_Brumadinho_03.jpg/1280px-Ahearn_Torres_Inhotim_Brumadinho_03.jpg",
            ],
            nome: 'Inhotim (Brumadinho)',
            categoria: 'regiao',
            regiao: 'Brumadinho (~60 km)',
            endereco: 'Rua B, 20 - Inhotim, Brumadinho',
            descricao: 'Maior museu de arte contemporânea a céu aberto do mundo, num jardim botânico gigante.',
            custo: 'caro',
            precoMedio: 110,
            faixaPreco: 'R$ 50-115 (ingresso) + transporte',
            temComida: true,
            ambiente: 'aberto',
            bebe: true,
            bebeObs: 'Caminhos longos; leve carrinho e protetor solar. Dia inteiro.',
            periodos: ['manha', 'tarde'],
            horarios: semana({ qua: ['09:30', '16:30'], qui: ['09:30', '16:30'], sex: ['09:30', '16:30'], sab: ['09:30', '17:30'], dom: ['09:30', '17:30'] }),
            nota: 4.8,
            avaliacoes: 52000,
            idealPessoas: { min: 1, max: 10 },
            tags: ['arte', 'natureza', 'bate-volta', 'dia inteiro', 'jardim'],
            motivo: 'Passeio de dia inteiro inesquecível; vale o programa especial.',
            destaqueHoje: false,
        },
        {
            id: 30,
            foto: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/In%C3%ADcio_Centro_Hist%C3%B3rico_de_Sabar%C3%A1.jpg/1280px-In%C3%ADcio_Centro_Hist%C3%B3rico_de_Sabar%C3%A1.jpg',
            galeria: [
              "https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Centro%2C_Sabar%C3%A1_-_MG%2C_Brazil_-_panoramio_%281%29.jpg/1280px-Centro%2C_Sabar%C3%A1_-_MG%2C_Brazil_-_panoramio_%281%29.jpg",
              "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Rio_das_Velhas_no_centro_hist%C3%B3rico_de_Sabar%C3%A1.jpg/1280px-Rio_das_Velhas_no_centro_hist%C3%B3rico_de_Sabar%C3%A1.jpg",
              "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Centro_Hist%C3%B3rico_de_Sabar%C3%A1_a_noite.jpg/1280px-Centro_Hist%C3%B3rico_de_Sabar%C3%A1_a_noite.jpg",
            ],
            nome: 'Centro Histórico de Sabará',
            categoria: 'regiao',
            regiao: 'Sabará (~25 km)',
            endereco: 'Centro Histórico - Sabará',
            descricao: 'Cidade colonial com igrejas barrocas, casario antigo e o famoso doce de cidra.',
            custo: 'barato',
            precoMedio: 30,
            faixaPreco: 'R$ 0 a passear / R$ 20-50 comendo',
            temComida: true,
            ambiente: 'aberto',
            bebe: true,
            bebeObs: 'Ruas de pedra (paralelepípedo) — carrinho balança; sling ajuda.',
            periodos: ['manha', 'tarde'],
            horarios: todaSemana('08:00', '18:00'),
            nota: 4.6,
            avaliacoes: 7800,
            idealPessoas: { min: 1, max: 8 },
            tags: ['histórico', 'barroco', 'bate-volta', 'tranquilo'],
            motivo: 'História colonial pertinho de BH, gasto baixo e bom passeio a dois.',
            destaqueHoje: false,
        },
        {
            id: 31,
            foto: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Vista_parcial_do_centro_hist%C3%B3rico_de_Sabar%C3%A1.jpg/1280px-Vista_parcial_do_centro_hist%C3%B3rico_de_Sabar%C3%A1.jpg",
            galeria: [
              "https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Centro%2C_Sabar%C3%A1_-_MG%2C_Brazil_-_panoramio_%281%29.jpg/1280px-Centro%2C_Sabar%C3%A1_-_MG%2C_Brazil_-_panoramio_%281%29.jpg",
              "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Centro_Hist%C3%B3rico_de_Sabar%C3%A1_a_noite.jpg/1280px-Centro_Hist%C3%B3rico_de_Sabar%C3%A1_a_noite.jpg",
            ],
            nome: 'Gruta da Lapinha (Lagoa Santa)',
            categoria: 'regiao',
            regiao: 'Lagoa Santa (~40 km)',
            endereco: 'Parque Estadual do Sumidouro - Lagoa Santa',
            descricao: 'Caverna iluminada com formações impressionantes, em parque com trilhas e museu.',
            custo: 'barato',
            precoMedio: 25,
            faixaPreco: 'R$ 15-30 (entrada)',
            temComida: true,
            ambiente: 'misto',
            bebe: false,
            bebeObs: 'Escadas e piso irregular dentro da gruta; difícil com bebê de colo.',
            periodos: ['manha', 'tarde'],
            horarios: semana({ ter: ['09:00', '16:30'], qua: ['09:00', '16:30'], qui: ['09:00', '16:30'], sex: ['09:00', '16:30'], sab: ['09:00', '16:30'], dom: ['09:00', '16:30'] }),
            nota: 4.5,
            avaliacoes: 6100,
            idealPessoas: { min: 2, max: 10 },
            tags: ['caverna', 'natureza', 'trilha', 'bate-volta'],
            motivo: 'Aventura barata e diferente a menos de 1h de BH.',
            destaqueHoje: false,
        },
        {
            id: 32,
            foto: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Pra%C3%A7a_da_Esta%C3%A7%C3%A3o%2C_Belo_Horizonte%2C_Brasil_1.JPG/1280px-Pra%C3%A7a_da_Esta%C3%A7%C3%A3o%2C_Belo_Horizonte%2C_Brasil_1.JPG",
            galeria: [
              "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Pra%C3%A7a_da_Esta%C3%A7%C3%A3o%2C_Belo_Horizonte%2C_Brasil_0.JPG/1280px-Pra%C3%A7a_da_Esta%C3%A7%C3%A3o%2C_Belo_Horizonte%2C_Brasil_0.JPG",
              "https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Pra%C3%A7a_da_Esta%C3%A7%C3%A3o%2C_Belo_Horizonte%2C_Brasil_2.JPG/1280px-Pra%C3%A7a_da_Esta%C3%A7%C3%A3o%2C_Belo_Horizonte%2C_Brasil_2.JPG",
              "https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Pra%C3%A7a_da_Esta%C3%A7%C3%A3o%2C_Belo_Horizonte%2C_Brasil.JPG/1280px-Pra%C3%A7a_da_Esta%C3%A7%C3%A3o%2C_Belo_Horizonte%2C_Brasil.JPG",
            ],
            nome: 'Praça da Estação (Praça Rui Barbosa)',
            categoria: 'praca',
            regiao: 'Centro',
            endereco: 'Praça Rui Barbosa - Centro',
            descricao: 'Grande esplanada em frente à estação, palco de eventos, feiras e shows ao ar livre.',
            custo: 'gratis',
            precoMedio: 0,
            faixaPreco: 'R$ 0',
            temComida: true,
            ambiente: 'aberto',
            bebe: true,
            bebeObs: 'Piso amplo e plano; ótimo pra carrinho fora dos dias de evento lotado.',
            periodos: ['tarde', 'noite'],
            horarios: vinte4h(),
            nota: 4.4,
            avaliacoes: 15300,
            idealPessoas: { min: 1, max: 15 },
            tags: ['esplanada', 'eventos', 'show', 'histórico', 'gratuito'],
            motivo: 'Espaço aberto enorme e gratuito; pega bem os eventos da cidade.',
            destaqueHoje: false,
        },
    ]
}
